# Imports

In [1]:
import string

In [12]:
from pathlib import Path
import sys

In [13]:
cwd = Path.cwd()

In [14]:
stanford_dir = cwd.parent / 'XCS224N-A1-master' / 'src'

In [15]:
sys.path.append(str(stanford_dir))

In [16]:
import sys
import os
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from utils import *
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import PCA

[nltk_data] Downloading package reuters to /Users/mukti/nltk_data...
[nltk_data]   Package reuters is already up-to-date!


# Solutions

*This is not the final code; some code was changed directly in the submission.py file. Submitted it online and got all points.*

## Problem 1, function 1 - get unique words

In [52]:
def distinct_words(corpus):
    """ Determine a list of distinct words for the corpus.
        Params:
            corpus (list of list of strings): corpus of documents
        Return:
()            corpus_words (list of strings): list of distinct words across the corpus, sorted (using python 'sorted' function)
            num_corpus_words (integer): number of distinct words across the corpus
    """
    corpus_words = []
    num_corpus_words = 0

    # ### START CODE HERE ###
    corpus_words = sorted(list({token for document in corpus for token in document if token.isalpha() or token in ['<START>','<END>']}))
    num_corpus_words = len(corpus_words)
    # ### END CODE HERE ###

    return corpus_words, num_corpus_words

**Create an example corpus containing just 2 lists in it.**

In [53]:
# example
c1 = '<START> all that glitters is not gold . <END>'
c2 = '<START> all is well that ends well . <END>'

corpus = [c1.split(), c2.split()]

In [54]:
corpus

[['<START>', 'all', 'that', 'glitters', 'is', 'not', 'gold', '.', '<END>'],
 ['<START>', 'all', 'is', 'well', 'that', 'ends', 'well', '.', '<END>']]

In [55]:
corpus_words, num_corpus_words = distinct_words(corpus)

In [56]:
corpus_words

['<END>',
 '<START>',
 'all',
 'ends',
 'glitters',
 'gold',
 'is',
 'not',
 'that',
 'well']

In [57]:
num_corpus_words

10

In [24]:
reuters_corpus = read_corpus()[100]

In [25]:
reuters_corpus

['<START>',
 'texaco',
 '&',
 'lt',
 ';',
 'txc',
 '>',
 'canada',
 'to',
 'raise',
 'crude',
 'oil',
 'postings',
 'texaco',
 'inc',
 "'",
 's',
 'texaco',
 'canada',
 'said',
 'it',
 'will',
 'raise',
 'postings',
 'for',
 'its',
 'edmonton',
 '/',
 'swann',
 'hills',
 'crude',
 'by',
 '24',
 'canadian',
 'cts',
 'a',
 'barrel',
 ',',
 'effective',
 'june',
 '20',
 '.',
 'the',
 'company',
 'said',
 'the',
 'new',
 'posting',
 'for',
 'edmonton',
 '/',
 'swann',
 'hills',
 'will',
 'be',
 '25',
 '.',
 '60',
 'dlrs',
 'a',
 'barrel',
 '.',
 'the',
 'price',
 'hike',
 'follows',
 'a',
 'round',
 'of',
 'crude',
 'oil',
 'price',
 'increases',
 'started',
 'late',
 'june',
 '17',
 'by',
 'sun',
 'co',
 '.',
 'the',
 'other',
 'major',
 'canadian',
 'crude',
 'suppliers',
 'raised',
 'prices',
 'june',
 '18',
 '.',
 '<END>']

## Problem 1, function 2 - get co-occurence matrix

In [69]:
def compute_co_occurrence_matrix(corpus, window_size=4):
    """ Compute co-occurrence matrix for the given corpus and window_size (default of 4).

        Note: Each word in a document should be at the center of a window. Words near edges will have a smaller
              number of co-occurring words.

              For example, if we take the document "START All that glitters is not gold END" with window size of 4,
              "All" will co-occur with "START", "that", "glitters", "is", and "not".

        Params:
            corpus (list of list of strings): corpus of documents
            window_size (int): size of context window
        Return:
            M (numpy matrix of shape (number of unique words in the corpus , number of unique words in the corpus)):
                Co-occurrence matrix of word counts.
                The ordering of the words in the rows/columns should be the same as the ordering of the words given by the distinct_words function.
            word2Ind (dict): dictionary that maps word to index (i.e. row/column number) for matrix M.
    """
    words, num_words = distinct_words(corpus)
    M = None
    word2Ind = {}

    # ### START CODE HERE ###
    # initialize a matrix of size num_words
    M = np.zeros((num_words,num_words))
    
    # create a dictionary that takes the sorted words list and then assigns an index to each
    # This dict will help in mapping the word pairs to add values in the M matrix
    word2Ind = {word: n for n, word in enumerate(words)}
    
    # create a clean corpus structure that eliminates characters but keeps the list of lists
    cleaned_corpus = [[token for token in document if token.isalpha() or token in ['<START>','<END>']] for document in corpus]
    
    # cleaned_corpus is a list of lists. Each list is a document.
    # Each list has strings
    for document in cleaned_corpus:
        # loop over each word that would be a center word
        for center_i in range(len(document)):
            # this will only select indices that span the window around the center word and within range
            # context_m is the index of a word present around the center word in a window of size window_size
            # get the center word and context word
            center_word = document[center_i]
            
            for context_m in filter(lambda x: 0 <= x < len(document) and x != center_i, 
                                    range(center_i-window_size,center_i+window_size+1)):
                
                # get context word
                context_word = document[context_m]         
                
                # access these words from the dictionary
                # Allot the row index of M to be for center words and column index for the context word
                if center_word in word2Ind and context_word in word2Ind:
                    M[word2Ind[center_word],word2Ind[context_word]] += 1
                    
    # ### END CODE HERE ###

    return M, word2Ind

In [70]:
corpus

[['<START>', 'all', 'that', 'glitters', 'is', 'not', 'gold', '.', '<END>'],
 ['<START>', 'all', 'is', 'well', 'that', 'ends', 'well', '.', '<END>']]

In [71]:
M, word2Ind = compute_co_occurrence_matrix(corpus,window_size=4)

In [72]:
M

array([[0., 0., 0., 1., 1., 1., 1., 1., 1., 2.],
       [0., 0., 2., 0., 1., 0., 2., 0., 2., 1.],
       [0., 2., 0., 1., 1., 0., 2., 1., 2., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1., 2.],
       [1., 1., 1., 0., 0., 1., 1., 1., 1., 0.],
       [1., 0., 0., 0., 1., 0., 1., 1., 1., 0.],
       [1., 2., 2., 1., 1., 1., 0., 1., 2., 2.],
       [1., 0., 1., 0., 1., 1., 1., 0., 1., 0.],
       [1., 2., 2., 1., 1., 1., 2., 1., 0., 2.],
       [2., 1., 1., 2., 0., 0., 2., 0., 2., 2.]])

In [73]:
word2Ind

{'<END>': 0,
 '<START>': 1,
 'all': 2,
 'ends': 3,
 'glitters': 4,
 'gold': 5,
 'is': 6,
 'not': 7,
 'that': 8,
 'well': 9}

## Problem 1, function 3 - transform matrix using SVD

In [63]:
from sklearn.decomposition import TruncatedSVD

In [74]:
def reduce_to_k_dim(M, k=2):
    """ Reduce a co-occurrence count matrix of dimensionality (num_corpus_words, num_corpus_words)
        to a matrix of dimensionality (num_corpus_words, k) using the following SVD function from Scikit-Learn:
            - http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html

        Params:
            M (numpy matrix of shape (number of unique words in the corpus , number of unique words in the corpus)): co-occurrence matrix of word counts
            k (int): embedding size of each word after dimension reduction
        Return:
            M_reduced (numpy matrix of shape (number of unique words in the corpus, k)): matrix of k-dimensioal word embeddings.
                    In terms of the SVD from math class, this actually returns U * S
    """
    np.random.seed(4355)
    n_iter = 10     # Use this parameter in your call to `TruncatedSVD`
    M_reduced = None
    print("Running Truncated SVD over %i words..." % (M.shape[0]))

    # ### START CODE HERE ###
    svd = TruncatedSVD(n_components=k,n_iter=n_iter)
    
    # Transform the matrix
    M_reduced = svd.fit_transform(M)
    # ### END CODE HERE ###

    print("Done.")
    return M_reduced

In [75]:
M_reduced = reduce_to_k_dim(M,k=2)

Running Truncated SVD over 10 words...
Done.


In [76]:
M_reduced.shape

(10, 2)

In [77]:
M_reduced

array([[ 2.51757677, -0.09706068],
       [ 3.04504687,  1.64023541],
       [ 3.39994784,  0.16221166],
       [ 2.32577504,  0.52854231],
       [ 2.11328485, -0.18879363],
       [ 1.51131468,  0.79361344],
       [ 4.10492166, -1.33451162],
       [ 1.82887385,  0.70520148],
       [ 4.10492166, -1.33451162],
       [ 4.22388595,  0.5528    ]])

In [78]:
M.shape

(10, 10)

## Rough work

In [103]:
list(map(lambda x: x + 2 ,range(-4,5)))

[-2, -1, 0, 1, 2, 3, 4, 5, 6]

In [105]:
for n in map(lambda x: x + 2 ,range(-4,5)):
    print(n)

-2
-1
0
1
2
3
4
5
6


In [137]:
x = np.zeros((3,3))

In [138]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [139]:
test_dict = {'cest':0,
             'un': 1,
             'dimanche':2}

In [140]:
x[test_dict['cest'],test_dict['un']] += 1

In [142]:
x

array([[0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])